[package]
name = "agenttrace-tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[dependencies]
agenttrace-core = { version = "0.7.1", path = "../agenttrace-core" }
anyhow.workspace = true
chrono.workspace = true
crossterm.workspace = true
ratatui.workspace = true
unicode-width = "0.2"
